const events = {
    INCREMENTAR : "INCREMENTAR_EVENTO",
    DECREMENTAR : "DECREMENTAR_EVENTO",
    CALCULAR: "CALCULO_SOLICITADO_EVENTO",
    CALCULO_REALIZADO: "CALCULO_REALIZADO_EVENTO",
    REGISTER: "CADASTRAR_EVENTO",
    MUDAR_TEMA: "MUDAR_TEMA_DA_PÁGINA",
}
